[[main]]
name = 'Home'
pageRef = '/'
weight = 10

[[main]]
name = 'Articles'
pageRef = '/articles/'
weight = 20

[[main]]
name = 'Blog'
pageRef = '/posts/'
weight = 30

[[main]]
name = 'Tags'
pageRef = '/tags/'
weight = 40
