exclude: [Gemfile, Gemfile.lock, Readme.md]
force_polling: true
host: 0.0.0.0
defaults:
  - scope:
      path: ""
    values:
      layout: "page"
  - scope:
      path: "articles"
    values:
      layout: "article"