baseURL: https://dhemery.com/
languageCode: en-us
title: Dale H. Emery
copyright: © 2003–2022 Dale H. Emery
disableKinds:
    - taxonomy
    - term
    - tags
markup:
    goldmark:
        renderer:
            unsafe: true
