baseURL = "https://dhemery.com"
languageCode = "en-us"
title = "Dale H. Emery"
copyright = "© 2003–2023 Dale H. Emery"
disableKinds = [
    "taxonomy",
    "term",
] 

theme = "Dale"

[markup.goldmark.renderer]
unsafe = true
